purchase_order_management/urls.py
from django.contrib import admin
from django.urls import path, re_path
from purchase_order_management import views

app_name = 'purchase_order_management'
urlpatterns = [
    # url for sign in page
    path('', views.user_sign_in, name = 'sign_in'),

    # url for sign up page
    path('sign_up/', views.user_sign_up, name = 'sign_up'),

    # url for sign out view
    path('sign_out/', views.user_sign_out, name = 'sign_out'),

    # url for users list
    path('user_list/', views.user_list, name = 'user_list'),

    #url for users list update modal
    path('user_list/update/<int:pk>', views.CustomUserUpdateView.as_view(), name = 'update_user_list'),

    # url for purchase form
    path('purchase_order_form/', views.purchase_order_form, name = 'purchase_order_form'),
    # url for purchase order list
    path('purchase_order_list/', views.purchase_list, name = 'purchase_order_list'),

    # url for purchase order list delete modal
    path('delete_purchase_order_list/<int:pk>/', views.PurchaseOrderDeleteView.as_view(), name='delete_purchase_order_list'),

    # url for purchase order list update modal
    path('update_purchase_order_list/<int:pk>/', views.PurchaseOrderUpdateView.as_view(), name='update_purchase_order_list'),

    
    # url for purchase order detail view
    path('purchase_order_list/detail/<int:pk>', views.purchase_order_list_details, name ='purchase_order_list_detail'),

    # url for client list
    path('client_list/', views.client_list, name ='client_list'),
    
    # url for client list create modal
    path('create_client_list/', views.ClientCreateView.as_view(), name ='create_client_list'),

    # url for client detail view
    path('client_list/detail/<int:pk>', views.client_list_details, name ='client_list_detail'),


    # url for process list
    path('process_list/', views.process_list, name ='process_list'),

    
    # url for process list delete modal
    path('delete_process_list/<int:pk>/', views.ProcessDeleteView.as_view(), name='delete_process_list'),

    # url for process list update modal
    path('update_process_list/<int:pk>/', views.ProcessUpdateView.as_view(), name='update_process_list'),

    # url for purchase order list detail update modal
    path('update_process_list_purchase_order_detail/<int:pk>/', views.PurchaseOrderProcessDetailUpdateView.as_view(), name='update_process_list_purchase_order_detail'),
    # url for purchase order list detail delete modal
    path('delete_process_list_purchase_order_detail/<int:pk>/', views.PurchaseOrderProcessDetailDeleteView.as_view(), name='delete_process_list_purchase_order_detail'),


    # url for purchase order list detail update modal
    path('update_process_list_vendor_detail/<int:pk>/', views.VendorProcessDetailUpdateView.as_view(), name='update_process_list_vendor_detail'),
    # url for purchase order list detail delete modal
    path('delete_process_list_vendor_detail/<int:pk>/', views.VendorProcessDetailDeleteView.as_view(), name='delete_process_list_vendor_detail'),

    # url for client purchase order list detail update modal
    path('update_purchase_order_list_client_detail/<int:pk>/', views.ClientPurchaseOrderDetailUpdateView.as_view(), name='update_purchase_order_list_client_detail'),
    # url for client purchase order list detail delete modal
    path('delete_purchase_order_list_client_detail/<int:pk>/', views.ClientPurchaseOrderDetailDeleteView.as_view(), name='delete_purchase_order_list_client_detail'),
    
    # url for vendor list
    path('vendor_list/', views.vendor_list, name ='vendor_list'),

    # url for vendor list create modal
    path('create_vendor_list/', views.VendorCreateView.as_view(), name ='create_vendor_list'),

    # url for vendor detail view
    path('vendor_list/detail/<int:pk>', views.vendor_list_details, name ='vendor_list_detail'),

    # url for submitting purchase order form
    path('purchase_order_form/submit/', views.purchase_order_form_submit, name='purchase_order_form_submit'),

    # url for profile page
    path('my_profile/', views.profile, name ='profile'),

    # url for report error page
    path('report_error/', views.report_error, name ='report_errors'),

     # url for Purchase Order Form
    path('purchase_order_summary/<int:purchase_order_id>/', views.purchase_order_summary, name='order_summary'),


]

royal_printers/urls.py
from django.contrib import admin
from django.urls import path, include
import purchase_order_management
from django.conf.urls import handler400,handler500
from purchase_order_management import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("purchase_order_management.urls")),
]

handler404 = views.error_404
handler500 = views.error_500

purchase_order_management/forms.py
from .models import PurchaseOrder, Client, Vendor, CustomUser, Process
from bootstrap_modal_forms.forms import BSModalForm
from django import forms

class PurchaseOrderForm(BSModalForm):

    class Meta:
        model = PurchaseOrder
        fields = ('purchase_order_amount','purchase_order_amount_due')

class ProcessForm(BSModalForm):

    class Meta:
        model = Process
        fields = ('process_amount','process_amount_due')

class ClientForm(BSModalForm):
    
    class Meta:
        model = Client
        exclude = ('pk',)

class VendorForm(BSModalForm):
    
    class Meta:
        model = Vendor
        exclude = ('pk',)

class CustomUserForm(BSModalForm):
    class Meta:
        model = CustomUser
        fields = ['user_role']

purchase_order_management/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, HttpResponseRedirect
from .models import PurchaseOrder, Client, Vendor, CustomUser, Paper, Process, Binding, CTP, SpecialProcess, RaiseUV, Varnish, Lamination, Positive, Printing, Punching, Pasting, Folding, Creasing, Punch, Block, FourCol
from bootstrap_modal_forms.generic import BSModalDeleteView, BSModalUpdateView, BSModalCreateView
from django.urls import reverse_lazy, reverse
from .forms import ClientForm, VendorForm, CustomUserForm, PurchaseOrderForm, ProcessForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.hashers import make_password
import datetime


# Create your views here.
@method_decorator(login_required, name='dispatch')
class CustomUserUpdateView(BSModalUpdateView):
    model = CustomUser
    template_name = 'purchase_order_management/user_list_update.html'
    form_class = CustomUserForm
    success_message = 'Success: User was updated.'
    success_url = reverse_lazy('purchase_order_management:user_list')

@method_decorator(login_required, name='dispatch')
class PurchaseOrderDeleteView(BSModalDeleteView):
    model = PurchaseOrder
    template_name = 'purchase_order_management/purchase_order_list_delete.html'
    success_message = 'Success: Purchase order was deleted.'
    success_url = reverse_lazy('purchase_order_management:purchase_order_list')

@method_decorator(login_required, name='dispatch')
class PurchaseOrderUpdateView(BSModalUpdateView):
    model = PurchaseOrder
    form_class = PurchaseOrderForm
    template_name = 'purchase_order_management/purchase_order_list_update.html'
    success_message = 'Success: Purchase Order was updated.'
    success_url = reverse_lazy('purchase_order_management:purchase_order_list')

@method_decorator(login_required, name='dispatch')
class ProcessDeleteView(BSModalDeleteView):
    model = Process
    template_name = 'purchase_order_management/process_list_delete.html'
    success_message = 'Success: Process was deleted.'
    success_url = reverse_lazy('purchase_order_management:process_list')

@method_decorator(login_required, name='dispatch')
class ProcessUpdateView(BSModalUpdateView):
    model = Process
    form_class = ProcessForm
    template_name = 'purchase_order_management/process_list_update.html'
    success_message = 'Success: Process was updated.'
    success_url = reverse_lazy('purchase_order_management:process_list')


@method_decorator(login_required, name='dispatch')
class PurchaseOrderProcessDetailDeleteView(BSModalDeleteView):
    model = Process
    template_name = 'purchase_order_management/process_list_delete.html'
    success_message = 'Success: Process was deleted.'

    def get_success_url(self,**kwargs):
        process = Process.objects.get(pk=self.kwargs['pk'])
        purchase_order_id = process.process_purchase_order_id
        return reverse_lazy('purchase_order_management:purchase_order_list_detail', kwargs={'pk': purchase_order_id })


@method_decorator(login_required, name='dispatch')
class PurchaseOrderProcessDetailUpdateView(BSModalUpdateView):
    model = Process
    form_class = ProcessForm
    template_name = 'purchase_order_management/process_list_update.html'
    success_message = 'Success: Process was updated.'

    def get_success_url(self,**kwargs):
        process = Process.objects.get(pk=self.kwargs['pk'])
        purchase_order_id = process.process_purchase_order_id
        return reverse_lazy('purchase_order_management:purchase_order_list_detail', kwargs={'pk': purchase_order_id })


@method_decorator(login_required, name='dispatch')
class ClientCreateView(BSModalCreateView):
    template_name = 'purchase_order_management/client_list_create.html'
    form_class = ClientForm
    success_message = 'Success: Client was created.'
    success_url = reverse_lazy('purchase_order_management:client_list')


@method_decorator(login_required, name='dispatch')
class VendorCreateView(BSModalCreateView):
    template_name = 'purchase_order_management/vendor_list_create.html'
    form_class = VendorForm
    success_message = 'Success: Vendor was created.'
    success_url = reverse_lazy('purchase_order_management:vendor_list')


@method_decorator(login_required, name='dispatch')
class VendorProcessDetailDeleteView(BSModalDeleteView):
    model = Process
    template_name = 'purchase_order_management/process_list_delete.html'
    success_message = 'Success: Process was deleted.'

    def get_success_url(self,**kwargs):
        process = Process.objects.get(pk=self.kwargs['pk'])
        vendor_id = process.process_vendor_id
        return reverse_lazy('purchase_order_management:vendor_list_detail', kwargs={'pk': vendor_id })

@method_decorator(login_required, name='dispatch')
class VendorProcessDetailUpdateView(BSModalUpdateView):
    model = Process
    form_class = ProcessForm
    template_name = 'purchase_order_management/process_list_update.html'
    success_message = 'Success: Process was updated.'

    def get_success_url(self,**kwargs):
        process = Process.objects.get(pk=self.kwargs['pk'])
        vendor_id = process.process_vendor_id
        return reverse_lazy('purchase_order_management:vendor_list_detail', kwargs={'pk': vendor_id })

@method_decorator(login_required, name='dispatch')
class ClientPurchaseOrderDetailDeleteView(BSModalDeleteView):
    model = PurchaseOrder
    template_name = 'purchase_order_management/purchase_order_list_delete.html'
    success_message = 'Success: Purchase order was deleted.'

    def get_success_url(self,**kwargs):
        purchase_order = PurchaseOrder.objects.get(pk=self.kwargs['pk'])
        client_id = purchase_order.purchase_order_client_id
        return reverse_lazy('purchase_order_management:client_list_detail', kwargs={'pk': client_id })

@method_decorator(login_required, name='dispatch')
class ClientPurchaseOrderDetailUpdateView(BSModalUpdateView):
    model = PurchaseOrder
    form_class = PurchaseOrderForm
    template_name = 'purchase_order_management/purchase_order_list_update.html'
    success_message = 'Success: Purchase Order was updated.'

    def get_success_url(self,**kwargs):
        purchase_order = PurchaseOrder.objects.get(pk=self.kwargs['pk'])
        client_id = purchase_order.purchase_order_client_id
        return reverse_lazy('purchase_order_management:client_list_detail', kwargs={'pk': client_id })

@login_required
def purchase_list(request):
    """Generates the list of all the purchase orders and the processes in each of the purchase order.
    Parameters: HttpRequest object
    Returns : Nothing"""

    user_role = request.user.user_role

    # Get all the purchase orders or raise a 404 exception if no purchase orders
    purchase_orders = PurchaseOrder.objects.all()

    # Generate the list of processes for each purchase order
    process_list = []
    for purchase_order in purchase_orders:
        # Getting all the processes in a purchase order.
        # and appending it to the above process_list.
        process_list.append(purchase_order.process_set.all())

    data = {
        'purchase_orders': zip(purchase_orders,process_list),
        'user_role': user_role
     }
    return render(request, 'purchase_order_management/purchase_order_list.html', data )

@login_required
def purchase_order_list_details(request, pk):
    user_role = request.user.user_role
    purchase_order = PurchaseOrder.objects.get(pk=pk)
    processes = purchase_order.process_set.all()

    data = { 
        'processes':processes,
        'user_role': user_role
    }
    return render(request,'purchase_order_management/purchase_order_detail_view.html',data)


@login_required
def process_list(request):
    """Generates the list of all the processes.
    Parameters: HttpRequest object
    Returns : Nothing"""

    user_role = request.user.user_role

    # Get all the processes or raise a 404 exception if no purchase orders
    processes = Process.objects.all()

    data = {
        'processes': processes,
        'user_role': user_role
     }
    return render(request, 'purchase_order_management/process_list.html', data )

@login_required
def client_list(request):
    """Generates the list of all the clients.
    Parameters: HttpRequest object
    Returns : Nothing"""
    user_role = request.user.user_role
    # Get all the clients.
    clients = Client.objects.all()
    clients_total_amount = {}
    clients_total_amount_due = {}
    for client in clients:
        total_amount = 0
        total_amount_due = 0
        for purchase_order in client.purchaseorder_set.all():
            total_amount += purchase_order.purchase_order_amount
            total_amount_due += purchase_order.purchase_order_amount_due
        clients_total_amount[client.pk]=total_amount
        clients_total_amount_due[client.pk]=total_amount_due

    data = {
        'clients': clients,
        'clients_total_amount': clients_total_amount,
        'clients_total_amount_due': clients_total_amount_due,
        'user_role': user_role
     }
    return render(request, 'purchase_order_management/client_list.html', data )

@login_required
def client_list_details(request, pk):
    user_role = request.user.user_role
    client = Client.objects.get(pk=pk)
    purchase_orders = client.purchaseorder_set.all()

    process_list = []
    for purchase_order in purchase_orders:
        # Getting all the processes in a purchase order.
        # and appending it to the above process_list.
        process_list.append(purchase_order.process_set.all())


    data = { 
        'purchase_orders': zip(purchase_orders,process_list),
        'user_role': user_role
    }
    return render(request,'purchase_order_management/client_detail_view.html',data)

@login_required
def vendor_list(request):
    """Generates the list of all the vendors.
    Parameters: HttpRequest object
    Returns : Nothing"""

purchase_order_management/templates/purchase_order_management/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<title>Royal Printers</title>


	<!-- Bootstrap CSS CDN -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	<!-- Our Custom CSS -->
	<link rel="stylesheet" href="{% static 'purchase_order_management/style.css' %}">
	<!-- Scrollbar Custom CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

	<!-- jQuery CDN - Slim version (=without AJAX) -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
	<!-- Popper.JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
	<!-- Bootstrap JS -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
	<!-- jQuery Custom Scroller CDN -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

	<!-- Font Awesome JS -->
	<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

	<!-- Block for CSS -->
	{% block stylesheets %}
	{% endblock stylesheets %}

	<!--Block for JS-->
	{% block scripts %}
	{% endblock scripts %}


</head>

<body>

	<div class="wrapper">

		<!-- SIDEBAR  -->
		<nav id="sidebar">
			<div class="sidebar-header">
				<h3>Royal Printers</h3>
			</div>

			<ul class="list-unstyled components">
				<li>
					<a href="{% url 'purchase_order_management:purchase_order_form' %}">Add a new Job/Purchase Order</a>
				</li>
				<li>
							<a href={% url 'purchase_order_management:purchase_order_list' %}>Purchase Orders		</a>
						</li>
				<li class="active">
					<a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Search</a>
					<ul class="collapse list-unstyled" id="homeSubmenu">
						<li>
							<a href={% url 'purchase_order_management:client_list' %}>Client Search</a>
						</li>
						<li>
							<a href={% url 'purchase_order_management:process_list' %}>Process Search</a>
						</li>
						<li>
							<a href={% url 'purchase_order_management:vendor_list' %}>Vendor Search</a>
						</li>
					</ul>
				</li>
				{% if user_role == 1 %}
				<li>
					<a href={% url 'purchase_order_management:user_list' %}>Users List</a>
				</li>
				{% endif %}
			</ul>
			<ul class="list-unstyled CTAs">
				<li>
					<a href={% url 'purchase_order_management:sign_out'%} class="btn btn-light">
						<font color="#7386D5">Logout</font>
					</a>
				</li>
				<li>
					<a href={% url 'purchase_order_management:report_errors' %} class="article">Report Error</a>
				</li>
			</ul>
		</nav>
		<!--SIDEBAR ENDS HERE-->
		<div id="content">
			<div class="container-fluid">
				<button type="button" id="sidebarCollapse" class="btn btn-info">
				<i class="fas fa-align-left"></i>
		</button>
		{% block content %}
		{% endblock %}
			</div>
		</div>

		{% block extrascripts %}
		{% endblock extrascripts %}
		<script type="text/javascript">
			$(document).ready(function() {
				$("#sidebar").mCustomScrollbar({
					theme: "minimal"
				});

				$('#sidebarCollapse').on('click', function() {
					$('#sidebar, #content').toggleClass('active');
					$('.collapse.in').toggleClass('in');
					$('a[aria-expanded=true]').attr('aria-expanded', 'false');
				});
			});

		</script>

</body>

</html>

purchase_order_management/templates/purchase_order_management/client_detail_view.html
{% extends 'purchase_order_management/base.html' %}

{% load staticfiles %}

{% block stylesheets %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
{% endblock %}

{% block scripts %}
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>

    <hr>

    <table id="purchaseOrderList">
        <thead>
            <tr>
                <th>Purchase Order ID</th>
                <th>Purchase Order Date</th>
                <th>Purchase Order Client Name</th>
                <th>Purchase Order Item</th>
                <th>Purchase Order Item Quantity</th>
                <th>Process List</th>
                <th>Amount</th>
                <th>Amount Due</th>
                <th>Summary</th>
                <th>Delete</th>
                <th>Update</th>
            </tr>
        </thead>
        <tbody>
            {% for purchase_order,process_list in purchase_orders %}
                <tr>
                    <td>{{purchase_order.pk}}</td>
                    <td>{{purchase_order.purchase_order_created_on}}</td>
                    <td>{{purchase_order.purchase_order_client_id.client_name}}</td>
                    <td>{{purchase_order.purchase_order_item}}</td>
                    <td>{{purchase_order.purchase_order_item_quantity}}</td>
                    <td>
                        {% for process in process_list %}
                            {{process.process_name}},
                        {% endfor %}
                    </td>
                    <td>{{purchase_order.purchase_order_amount}}</td>
                    <td>{{purchase_order.purchase_order_amount_due}}</td>
                    <td>
                        <center>
                            <button type="button" class="btn btn-sm btn-primary">
                                Summary
                            </button>
                        </center>
                    </td>
                    <td>
                        <center>
                            <button type="button" class="delete-purchase-order-list btn btn-sm btn-danger" data-id="{% url 'purchase_order_management:delete_purchase_order_list_client_detail' purchase_order.pk %}">
                                <span class="fa fa-trash"></span>
                            </button>
                        </center>
                    </td>
                    <td>
                        <center>
                            <button type="button" class="update-purchase-order-list btn btn-sm btn-primary" data-id="{% url 'purchase_order_management:update_purchase_order_list_client_detail' purchase_order.pk %}">
                                <span class="fa fa-pencil">Update</span>
                            </button>
                        </center>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
        </tfoot>
    </table>

{% endblock %}

{% block extrascripts %}

    <script>
        $(document).ready( function () {
            $('#purchaseOrderList').DataTable();
        } );
    </script>

    <script type="text/javascript">
        $(function () {
            
            $(".delete-purchase-order-list").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
            });

            $(".update-purchase-order-list").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
            });

        });
    </script>
    
{% endblock%}

purchase_order_management/templates/purchase_order_management/purchase_order_list.html
{% extends 'purchase_order_management/base.html' %}

{% load staticfiles %}

{% block stylesheets %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
{% endblock %}

{% block scripts %}
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>

    <hr>

    <table id="purchaseOrderList">
        <thead>
            <tr>
                <th>Purchase Order ID</th>
                <th>Purchase Order Date</th>
                <th>Purchase Order Client Name</th>
                <th>Purchase Order Item</th>
                <th>Purchase Order Item Quantity</th>
                <th>Process List</th>
                <th>Amount</th>
                <th>Amount Due</th>
                <th>Summary</th>
                <th>Delete</th>
                <th>Update</th>
            </tr>
        </thead>
        <tbody>
            {% for purchase_order,process_list in purchase_orders %}
                <tr>
                    <td><a href={% url 'purchase_order_management:purchase_order_list_detail' purchase_order.pk %}>{{purchase_order.pk}}</a></td>
                    <td>{{purchase_order.purchase_order_created_on}}</td>
                    <td>{{purchase_order.purchase_order_client_id.client_name}}</td>
                    <td>{{purchase_order.purchase_order_item}}</td>
                    <td>{{purchase_order.purchase_order_item_quantity}}</td>
                    <td>
                        {% for process in process_list %}
                            {{process.process_name}},
                        {% endfor %}
                    </td>
                    <td>{{purchase_order.purchase_order_amount}}</td>
                    <td>{{purchase_order.purchase_order_amount_due}}</td>
                    <td>
                        <center>
                            <button type="button" class="btn btn-sm btn-primary">
                               <a href="{% url 'purchase_order_management:order_summary' purchase_order_id=purchase_order.pk %}">
                                Summary
                                </a>
                            </button>
                        </center>
                    </td>
                    <td>
                        <center>
                            <button type="button" class="delete-purchase-order-list btn btn-sm btn-danger" data-id="{% url 'purchase_order_management:delete_purchase_order_list' purchase_order.pk %}">
                                <span class="fa fa-trash"></span>
                            </button>
                        </center>
                    </td>
                    <td>
                        <center>
                            <button type="button" class="update-purchase-order-list btn btn-sm btn-primary" data-id="{% url 'purchase_order_management:update_purchase_order_list' purchase_order.pk %}">
                                <span class="fa fa-pencil">Update</span>
                            </button>
                        </center>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
        </tfoot>
    </table>

{% endblock %}

{% block extrascripts %}

    <script>
        $(document).ready( function () {
            $('#purchaseOrderList').DataTable();
        } );
    </script>

    <script type="text/javascript">
        $(function () {
            
            $(".delete-purchase-order-list").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
            });

            $(".update-purchase-order-list").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
            });

        });
    </script>
    
{% endblock%}

purchase_order_management/templates/purchase_order_management/user_list.html
{% extends 'purchase_order_management/base.html' %}

{% load staticfiles %}

{% block stylesheets %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
{% endblock %}

{% block scripts %}
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
{% endblock %}

{% block content %}

    <div class="modal fade" tabindex="-1" role="dialog" id="modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>

    <hr>

    <table id="userList" class="display" >
		<thead>
			<tr>
				<th class="text-center" scope="col">#</th>
				<th class="text-center" scope="col">User Name</th>
                <th class="text-center" scope="col">Role</th>
				<th class="text-center" scope="col">Last Login</th>
                <th class="text-center" scope="col">Update</th>
			</tr>
		</thead>
		<tbody>
			{% for user in users %}
			<tr>
				<th class="text-center" scope="row">{{ forloop.counter }}</th>
                <td class="text-center">{{ user.username }}</td>
                <td class="text-center">
                    {% if user.user_role == 1 %}
                        Super Admin
                    {% else %}
                        Admin
                    {% endif %}
                </td>
				<td class="text-center">{{ user.last_login }}</td>
                <td>
                    <center>
                        <button type="button" class="update-user-list btn btn-sm btn-primary" data-id="{% url 'purchase_order_management:update_user_list' user.pk %}">
                            <span class="fa fa-pencil"></span>
                        </button>
                    </center>
                </td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

{% endblock %}

{% block extrascripts %}

    <script>
        $(document).ready( function () {
            $('#userList').DataTable();
        } );
    </script>

    <script type="text/javascript">
        $(function () {
            // Update user list
            $(".update-user-list").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
            });

        });
    </script>  

</script>    
{% endblock%}